# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ultra96v2_0.xdc

# Block Designs: bd/ultra96v2_bd/ultra96v2_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_bd || ORIG_REF_NAME==ultra96v2_bd} -quiet] -quiet

# IP: bd/ultra96v2_bd/ip/ultra96v2_bd_zynq_ultra_ps_e_0_0/ultra96v2_bd_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_bd_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==ultra96v2_bd_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/ultra96v2_bd/ip/ultra96v2_bd_axi_gpio_0_0/ultra96v2_bd_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_bd_axi_gpio_0_0 || ORIG_REF_NAME==ultra96v2_bd_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ultra96v2_bd/ip/ultra96v2_bd_xbar_0/ultra96v2_bd_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_bd_xbar_0 || ORIG_REF_NAME==ultra96v2_bd_xbar_0} -quiet] -quiet

# IP: bd/ultra96v2_bd/ip/ultra96v2_bd_ps8_0_axi_periph_1/ultra96v2_bd_ps8_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_bd_ps8_0_axi_periph_1 || ORIG_REF_NAME==ultra96v2_bd_ps8_0_axi_periph_1} -quiet] -quiet

# IP: bd/ultra96v2_bd/ip/ultra96v2_bd_rst_ps8_0_100M_1/ultra96v2_bd_rst_ps8_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_bd_rst_ps8_0_100M_1 || ORIG_REF_NAME==ultra96v2_bd_rst_ps8_0_100M_1} -quiet] -quiet

# IP: bd/ultra96v2_bd/ip/ultra96v2_bd_axi_gpio_0_1/ultra96v2_bd_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_bd_axi_gpio_0_1 || ORIG_REF_NAME==ultra96v2_bd_axi_gpio_0_1} -quiet] -quiet

# IP: bd/ultra96v2_bd/ip/ultra96v2_bd_axi_bram_ctrl_0_0/ultra96v2_bd_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_bd_axi_bram_ctrl_0_0 || ORIG_REF_NAME==ultra96v2_bd_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/ultra96v2_bd/ip/ultra96v2_bd_blk_mem_gen_0_0/ultra96v2_bd_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_bd_blk_mem_gen_0_0 || ORIG_REF_NAME==ultra96v2_bd_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/ultra96v2_bd/ip/ultra96v2_bd_axi_uart16550_0_0/ultra96v2_bd_axi_uart16550_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_bd_axi_uart16550_0_0 || ORIG_REF_NAME==ultra96v2_bd_axi_uart16550_0_0} -quiet] -quiet

# IP: bd/ultra96v2_bd/ip/ultra96v2_bd_auto_ds_0/ultra96v2_bd_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_bd_auto_ds_0 || ORIG_REF_NAME==ultra96v2_bd_auto_ds_0} -quiet] -quiet

# IP: bd/ultra96v2_bd/ip/ultra96v2_bd_auto_pc_0/ultra96v2_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_bd_auto_pc_0 || ORIG_REF_NAME==ultra96v2_bd_auto_pc_0} -quiet] -quiet

# IP: bd/ultra96v2_bd/ip/ultra96v2_bd_auto_ds_1/ultra96v2_bd_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_bd_auto_ds_1 || ORIG_REF_NAME==ultra96v2_bd_auto_ds_1} -quiet] -quiet

# IP: bd/ultra96v2_bd/ip/ultra96v2_bd_auto_pc_1/ultra96v2_bd_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_bd_auto_pc_1 || ORIG_REF_NAME==ultra96v2_bd_auto_pc_1} -quiet] -quiet

# IP: bd/ultra96v2_bd/ip/ultra96v2_bd_auto_ds_2/ultra96v2_bd_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_bd_auto_ds_2 || ORIG_REF_NAME==ultra96v2_bd_auto_ds_2} -quiet] -quiet

# IP: bd/ultra96v2_bd/ip/ultra96v2_bd_auto_ds_3/ultra96v2_bd_auto_ds_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_bd_auto_ds_3 || ORIG_REF_NAME==ultra96v2_bd_auto_ds_3} -quiet] -quiet

# IP: bd/ultra96v2_bd/ip/ultra96v2_bd_auto_pc_2/ultra96v2_bd_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_bd_auto_pc_2 || ORIG_REF_NAME==ultra96v2_bd_auto_pc_2} -quiet] -quiet

# XDC: bd/ultra96v2_bd/ultra96v2_bd_ooc.xdc
